import pytest
import os
from day8 import part2

def test_unique_amount_of_anti_nodes_with_harmonic_frequencies():
    file_name = write_to_temp_file("""T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........""")
    anti_nodes = part2.unique_amount_of_anti_nodes(file_name)
    assert anti_nodes == 9

def test_unique_amount_of_anti_nodes_with_harmonic_frequencies_and_multiple_antennae():
    file_name = write_to_temp_file("""............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............""")
    anti_nodes = part2.unique_amount_of_anti_nodes(file_name)
    assert anti_nodes == 34

def test_full_input():
    anti_nodes = part2.unique_amount_of_anti_nodes('advent-of-code/day8/input.txt')
    assert anti_nodes == 1067

def write_to_temp_file(text):
    file = open("test_input.txt", "w")
    file.write(text)
    file.close
    return os.path.realpath(file.name)