import pytest
import os
from day8 import part1

def test_unique_amount_of_anti_nodes():
    file_name = write_to_temp_file("""............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............""")
    anti_nodes = part1.unique_amount_of_anti_nodes(file_name)
    assert anti_nodes == 14

def test_full_input():
    anti_nodes = part1.unique_amount_of_anti_nodes('advent-of-code/day8/input.txt')
    assert anti_nodes == 278

def write_to_temp_file(text):
    file = open("test_input.txt", "w")
    file.write(text)
    file.close
    return os.path.realpath(file.name)